version: '3'

services:
  astran-backend:
    build: ./backend
    container_name: astran-backend
    environment:
      - ALPHAVANTAGE_KEY='EUO9GYYOSFISLBH4'
    ports:
      - 3001:3001

  astran-frontend:
    build: ./frontend
    container_name: astran-frontend
    ports:
      - 3000:3000
    links:
      - astran-backend